workspaces:
- name: the-app
  path: ./packages/my-app/.github/workflows
  package_json: ./packages/my-app
- name: my-second-app
  path: ./packages/my-second-app/.github/workflows
  package_json: null
target: .github/workflows
