name: CD
on:
  push:
    tags:
      - "**"
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -r

      # Release on MacOS
      - name: Prepare MacOS Release
        if: matrix.os == 'macos-latest'
        run: |
          strip target/release/hawk
          mkdir -p release
          tar -C ./target/release -czvf ./release/hawk-macos.tar.gz ./hawk

      # Release on Linux
      - name: Prepare Linux Release
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo deb
          strip target/release/hawk
          mkdir -p release
          mv target/debian/*.dev ./release/hawk-linux.deb
          tar -C ./target/release -czvf ./release/hawk-linux.tar.gz ./hawk

      - name: Prepare Windows Release
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p release
          tar -C ./target/release -czvf ./release/hawk-win.tar.gz ./hawk.exe

      - name: Release
        uses: softprops/actions-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          draft: true
          files: |
            ./release/*.tar.gz
            ./release/*.zip
            ./release/*.deb
